### ISSUE TITLE
does this support virtualizing osx/macos?

### ISSUE THREAD

**Issue by sabujp** [veertuinc/vdhh#1]
So re-reading the description (" for macOS platforms to run Linux and Windows VMS") and looking for "efi" in the code, it looks like it can't boot osx/macos. Are you planning on open sourcing efi support?

**Comment by medicis123** [comment]
We are implementing a very different approach to address osx/macos VMs with server-level virtualization, which will address performance issues for boot times etc. Stay tuned.

**Comment by sabujp** [comment]
If you're building something like esxi, please make sure the graphics performance is on par or better than esxi, i.e. run some xcode ios simulator tests.

**Comment by medicis123** [comment]
Hi, Yes. OpenGL is on the roadmap. The first release(due soon) will address IOPS, boot time performance, followed by OpenGL support. Would love to find out specific requirements.

**Comment by silkimen** [comment]
> We are implementing a very different approach to address osx/macos VMs with server-level virtualization, which will address performance issues for boot times etc. Stay tuned.

Hey guys, what exactly do you mean by server-level virtualization? Do you plan to build a container environment, like LXC or Docker just for OSX? That's the kind of software I'm actually looking for!

**Comment by medicis123** [comment]
Sefa - please send us an email at support@veertu.com.
