### ISSUE TITLE
Nested VMX

### ISSUE THREAD

**Issue by adrianlshaw** [veertuinc/vdhh#14]
Are there any plans to support nested VMX for booting a guest hypervisor? VirtualBox doesn't support this and the only commercial OS X solution that can do it is VMware Fusion.

**Comment by mkt4** [comment]
Hi,

We don't support nested VMX, this would be very challenging to get hypervisor.framework support nested VMX at a descent performance, due to the lack of control of address space caching.

Thank.ss
