### ISSUE TITLE
Latest update breaks Windows networking

### ISSUE THREAD

**Issue by davejlong** [veertuinc/vdhh#15]
Since the latest version (1.2.96), networking is not working on my Windows 10 guest. I've tried setting the network card on the guest to bridged and shared, but the network adapted in version is not able to get an IP address from DHCP.

```
$ ipconfig

Windows IP Configuration


Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::99f9:d14a:455f:f60d%5
   Autoconfiguration IPv4 Address. . : 169.254.246.13
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :
```

Host OS:
```
$ uname -a
Darwin Compe.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
```

Guest OS:
```
$ ver
Microsoft Windows [Version 10.0.14393]
```

**Comment by catflight** [comment]
Please try to reset the MAC address to Automatic in the VM settings. Btw, are you aware of incompatibility of Bridged mode with wireless interfaces?

**Comment by davejlong** [comment]
I don't know what happened, but rebooting a few times fixed it. Rebooting once or twice wasn't enough apparently. It was the third time rebooting to get it working.
