### ISSUE TITLE
errors when building from source

### ISSUE THREAD

**Issue by samdmarshall** [veertuinc/vdhh#21]
Hi, I was attempting to build this locally from source when i ran into an issue with the dependencies being resolved to outside of the `PROJECT_DIR`. The readme only details the build command to issue to `xcodebuild`, but the project seems to be missing schemes on a fresh clone (not a huge deal to auto-create those) but then i ran into problems with resolving the `glib`, `libarchive`, and `pixman` dependencies. Could you please either include these sources or include some sort of dependency pinning so that other developers can work on this project without having to hap-hazard guess what what versions are compatible and how to install them correctly without doing major work on the contents of the xcodeproj files please?

Thanks!

**Comment by mkt4** [comment]
Hi,

it might be easier to you to build the source from the complete snapshot we are using to build it, it include UI and other things that might not be interested to you, but the build process will be easier as it include glib/libarchive/pixman dependencies (and some more as well)
contact support@veertu.com and we will send you the bulild snapshot

**Comment by samdmarshall** [comment]
Is there any chance that this process could be open sourced and made more accessible for people that want to hack on or contribute to the code?

**Comment by mkt4** [comment]
Hi,

It is open source we just believed that majority of opensource community would be interesting more in the raw hypervisor other than the ui stuff, this is why we are sending the ui per request by email...

**Comment by samdmarshall** [comment]
tbh i was looking at removing all of the UI from the app first and use it as a command line tool, but it is hard to start on that when the base code doesn't build out of the box :\

**Comment by mkt4** [comment]
Hi,

Just send us the mail to support@gmail.com and you get the entire UI package under gplv2 that you can modify to command line the way that you want...

**Comment by mkt4** [comment]
Hi, sorry I saw i miss typed the address, I meant support@veertu.com
