### ISSUE TITLE
Take snapshot for virtual machines

### ISSUE THREAD

**Issue by wengych** [veertuinc/vdhh#23]
With libvirt ort qemu-img, we can create snapshot for virtual machine or virtual disk.
How does vdhh?

**Comment by mkt4** [comment]
You can use the same snapshot inside vdhh that you created with qemu-img and libvirt, the only problem is that the UI does not include the concept of snapshot handling

**Comment by wengych** [comment]
I've installed qemu by homebrew so I have qemu-img command on my local.
Is it possible to create new.img disk image file by `qemu-img create -f qcow2 -o backing_file=old.img new.img` and use it as the running layer for vm?

**Comment by mkt4** [comment]
It was never tried, but should just work (unless there is a bug somewhere)
