### ISSUE TITLE
Design: Application Icon has misplaced pixels (redesign?)

### ISSUE THREAD

**Issue by cybertim** [veertuinc/vdhh#4]
The misplaced/coloured pixels are circled red:
![screen shot 2016-11-02 at 08 01 31](https://cloud.githubusercontent.com/assets/5379564/19919463/4625241e-a0d3-11e6-8c9a-b0a2ad813aad.png)
I would suggest redesigning the whole icon (give it more depth, better outline etc.) to make it look more natural among other osx applications.

**Comment by catflight** [comment]
Thanks for your comment, actually we have artwork in better quality, looks build process fails to select correct images for certain resolutions - this is main problem. May be you are right - adding some kind of shadows will make the icon more organic in row of other dock apps)

**Comment by catflight** [comment]
Improved in version 91
