### ISSUE TITLE
vmx triggers discrete GPU switch 

### ISSUE THREAD

**Issue by kruckenb** [veertuinc/vdhh#9]
When a vm is started, whether it's headless or not, discrete GPU is used (I tested on MacBook Pro Retina mid-2012 with MacOS 10.11.5, running Ubuntu Server 16.04.1 LTS in a Veertu VM).

Activity Monitor shows that both Veertu Desktop and the VM process are flagged as "Requires High Performance GPU" (not sure why the Desktop would need that). Watching "Dependencies" in gfsCardStatus (v2.3) shows that Veertu Desktop doesn't trigger the discrete GPU, but the vmx process does. I'm not using the Ubuntu desktop, just the console, but even in headless mode the vmx process still triggers the discrete GPU.

Main concern about this is that the discrete GPU burns more battery and that's especially a problem for long-running VM's I typically use. On a related note, VMware Fusion seems to have had problems with this same issue in early versions.

**Comment by mkt4** [comment]
I was sure this issue was fixed, let me check it and come back to you.

Thanks.

**Comment by kruckenb** [comment]
I should have mentioned, I'm running Veertu 1.2 (90), just installed
yesterday.

**Comment by catflight** [comment]
Fixed in version 91

**Comment by kruckenb** [comment]
@catflight Thanks. How do I get version 91?

**Comment by catflight** [comment]
The update is in CDN and will arrive to local caches in next 20 hours. To avoid caches and get fresh version immediately please try to
```
curl https://d2sje6b9huarvp.cloudfront.net/VeertuDesktop-1.2.91.dmg > VeertuDesktop-1.2.91.dmg
```
